import TaskItem from "./TaskItem"
function TaskFieldSB2 () {
    return(
        <>
        <ol>
            <TaskItem />
            <li>This will be a list of tasks that is generated by a map function</li>
        </ol>
        </>
    )
}
export default TaskFieldSB2